import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,replan,rollover,toggleTask,moveTask,validateState,range,diffDays,weight,prevTask,TOPICS,START,LEARN_END,REV_START,END} from '../dist/planner.js';
function scheduleInvariants(s){assert.equal(s.tasks.length,63);assert.equal(new Set(s.tasks.map(t=>t.id)).size,63);for(const t of s.tasks){if(!t.date)continue;if(!t.doneAt)assert.ok(t.date<=END);if(t.stage>0){const prev=prevTask(s,t);assert.ok(prev.date);assert.ok(t.date>=REV_START);assert.ok(diffDays(t.date,prev.doneAt||prev.date)>=(t.stage===1?1:3),t.id);}}}
test('21 topics, 63 sessions, two ordered spaced revisions before the exam',()=>{const s=createState(START);scheduleInvariants(s);assert.equal(TOPICS.length,21);assert.equal(s.tasks.filter(t=>t.date).length,63);for(const t of s.tasks.filter(t=>t.stage===0))assert.ok(t.date>=START&&t.date<=LEARN_END);assert.equal(s.notices.length,0);});
test('equal days are balanced; weekends have more sessions',()=>{const s=createState(START);const counts=range(START,LEARN_END).map(d=>({d,count:s.tasks.filter(t=>t.stage===0&&t.date===d).length,w:weight(s,d)}));const normal=counts.filter(x=>x.w===1),heavy=counts.filter(x=>x.w===2);assert.ok(Math.max(...normal.map(x=>x.count))-Math.min(...normal.map(x=>x.count))<=1);assert.ok(heavy.every(x=>x.count>=Math.max(...normal.map(x=>x.count))));});
test('missed work carries, completed work stays done, rollover is idempotent',()=>{const s=createState(START);const id=s.tasks.find(t=>t.date===START&&t.stage===0).id;toggleTask(s,id,START);rollover(s,'2026-09-21');scheduleInvariants(s);assert.equal(s.tasks.find(t=>t.id===id).doneAt,START);assert.ok(s.tasks.filter(t=>!t.doneAt).every(t=>!t.date||t.date>='2026-09-21'));assert.ok(s.tasks.some(t=>t.rolledFrom));const snapshot=JSON.stringify(s);assert.equal(rollover(s,'2026-09-21'),false);assert.equal(JSON.stringify(s),snapshot);});
test('off days stay empty, light days have less load',()=>{const s=createState(START);s.overrides['2026-09-19']='off';s.overrides['2026-09-20']='light';replan(s,START);assert.equal(s.tasks.filter(t=>t.date==='2026-09-19').length,0);assert.ok(s.tasks.filter(t=>t.date==='2026-09-20').length<=s.tasks.filter(t=>t.date==='2026-09-21').length);scheduleInvariants(s);});
test('all days off retains every session and reports infeasibility',()=>{const s=createState(START);s.weekly=Array(7).fill('off');replan(s,START);assert.equal(s.tasks.length,63);assert.ok(s.tasks.every(t=>t.date===null));assert.ok(s.notices.some(n=>n.includes('cannot fit')));});
test('move pins a session; swap exchanges dates; invalid moves are atomic',()=>{const s=createState(START);const a=s.tasks.find(t=>t.stage===0&&t.date==='2026-09-18'),b=s.tasks.find(t=>t.stage===0&&t.date==='2026-09-19');moveTask(s,a.id,b.date,START,b.id);assert.equal(s.tasks.find(t=>t.id===a.id).date,'2026-09-19');assert.equal(s.tasks.find(t=>t.id===b.id).date,'2026-09-18');replan(s,START);assert.equal(s.tasks.find(t=>t.id===a.id).date,'2026-09-19');const before=JSON.stringify(s);assert.throws(()=>moveTask(s,a.id,'2026-09-27',START));assert.equal(JSON.stringify(s),before);scheduleInvariants(s);});
test('reviews cannot be ticked before watching or without spacing',()=>{const s=createState(START),id=s.tasks[0].topicId;assert.throws(()=>toggleTask(s,`${id}:1`,REV_START));toggleTask(s,`${id}:0`,START);assert.throws(()=>toggleTask(s,`${id}:1`,'2026-09-26'));toggleTask(s,`${id}:1`,REV_START);assert.throws(()=>toggleTask(s,`${id}:2`,'2026-09-28'));toggleTask(s,`${id}:2`,'2026-09-30');assert.throws(()=>toggleTask(s,`${id}:0`,'2026-09-29'));assert.ok(s.tasks.find(t=>t.id===`${id}:2`).doneAt);});
test('late missed videos remain tracked; impossible deadline is reported',()=>{const s=createState(START);rollover(s,'2026-10-13');assert.equal(s.tasks.length,63);assert.ok(s.notices.length);assert.ok(s.tasks.some(t=>!t.date));});
test('backup validation rejects missing, duplicate, malformed sessions and invalid order',()=>{const s=createState(START);assert.deepEqual(validateState(JSON.parse(JSON.stringify(s))).tasks,s.tasks);assert.throws(()=>validateState({}));let raw=structuredClone(s);raw.tasks[0]=raw.tasks[1];assert.throws(()=>validateState(raw));raw=structuredClone(s);raw.tasks[0].date='2026-09-99';assert.throws(()=>validateState(raw));raw=structuredClone(s);raw.tasks[1].doneAt=REV_START;assert.throws(()=>validateState(raw));});
test('a full daily completion simulation reaches 63 by October 14',()=>{const s=createState(START);for(const d of range(START,END)){rollover(s,d);for(const t of [...s.tasks.filter(t=>t.date===d&&!t.doneAt)].sort((a,b)=>a.stage-b.stage))toggleTask(s,t.id,d);scheduleInvariants(s);}assert.equal(s.tasks.filter(t=>t.doneAt).length,63);});
test('a missed weekend recovers all sessions by the exam',()=>{const s=createState(START);for(const d of range(START,END)){rollover(s,d);if(['2026-09-19','2026-09-20','2026-10-03'].includes(d))continue;for(const t of [...s.tasks.filter(t=>t.date===d&&!t.doneAt)].sort((a,b)=>a.stage-b.stage))toggleTask(s,t.id,d);}assert.equal(s.tasks.filter(t=>t.doneAt).length,63);});
test('many workload combinations preserve task count, order and deadlines',()=>{for(let n=0;n<80;n++){const s=createState(START);s.weekly=Array.from({length:7},(_,i)=>['off','light','normal','heavy'][(n>>(i%4))%4]);replan(s,START);scheduleInvariants(s);}});

test('extended first pass reduces September 19 and includes September 26',()=>{const s=createState(START);assert.equal(s.tasks.filter(t=>t.stage===0&&t.date==='2026-09-19').length,3);assert.ok(s.tasks.some(t=>t.stage===0&&t.date==='2026-09-26'));assert.ok(s.tasks.filter(t=>t.stage>0).every(t=>t.date>='2026-09-27'));scheduleInvariants(s);});
test('existing saved plans rebalance once without losing progress or manual moves',()=>{const s=createState(START);toggleTask(s,'eye-1:0',START);moveTask(s,'eye-2:0','2026-09-23',START);delete s.scheduleRevision;for(const t of s.tasks)if(!t.doneAt&&!t.pinned&&t.stage===0&&t.date==='2026-09-26')t.date='2026-09-19';assert.equal(rollover(s,START),true);assert.equal(s.tasks.find(t=>t.id==='eye-1:0').doneAt,START);assert.equal(s.tasks.find(t=>t.id==='eye-2:0').date,'2026-09-23');assert.equal(s.tasks.find(t=>t.id==='eye-2:0').pinned,true);assert.ok(s.tasks.some(t=>t.stage===0&&t.date==='2026-09-26'));assert.equal(rollover(s,START),false);scheduleInvariants(s);});
